### PR TITLE
Karbon Lib Tasks

### PR DESCRIPTION
**Pull request by aalekhneema**

### CODE REVIEW

**Review by charanteja333 — CHANGES_REQUESTED** [review]
Can you add script to create karbon cluster as well?

**Comment by charanteja333** [comment]
Also add scripts for upgrade of OS image , Functions that are possible from UI

**Comment by aalekhneema** [comment]
> Can you add script to create karbon cluster as well?

**Comment by aalekhneema** [comment]
> Can you add script to create karbon cluster as well?

cluster create , import images and enable karbon are there within Karbon.py.

**Review by charanteja333 — APPROVED** [review]

**Pull request merged**
